#!/bin/bash

print_title() {
  clear
  echo -e "\e[1;34m"
  echo "  _____                  _____                  _   _                 _           _          "
  echo " |_   _|                |  __ \                | | (_)               | |         | |         "
  echo "   | |  _ __ ___   ___  | |  | | ___  ___  ___ | |_ _  ___  _ __  ___| |_ ___  __| | ___ _ __ "
  echo "   | | | '_ \` _ \ / _ \ | |  | |/ _ \/ __|/ _ \| __| |/ _ \| '_ \/ __| __/ _ \/ _\` |/ _ \ '__|"
  echo "  _| |_| | | | | |  __/ | |__| |  __/\__ \ (_) | |_| | (_) | | | \__ \ ||  __/ (_| |  __/ |   "
  echo " |_____|_| |_| |_|\___| |_____/ \___||___/\___/ \__|_|\___/|_| |_|___/\__\___|\__,_|\___|_|   "
  echo -e "\e[0m"
  echo -e "\e[1;33mTop 3 Ferramentas Amigáveis\e[0m"
  echo
}

print_menu() {
  echo -e "\e[1;32mEscolha uma opção:\e[0m"
  echo "1) Entrar no link"
  echo "2) Sair"
  echo
  read -p "Digite o número da opção e pressione Enter: " choice
}

open_link() {
  termux-open "https://youtube.com/shorts/lQf24ROXU9E?si=YtCsjhEObwb2rDjX"
  echo -e "\nLink aberto no navegador!"
  sleep 2
}

while true; do
  print_title
  print_menu

  case $choice in
    1)
      open_link
      break
      ;;
    2)
      clear
      echo "Saindo da ferramenta..."
      sleep 1
      break
      ;;
    *)
      echo -e "\e[1;31mOpção inválida! Tente novamente.\e[0m"
      sleep 1
      ;;
  esac
done
0
